const bcrypt = require('bcrypt');
const pool   = require('../config/db');

const SOLSTICE_EMAIL    = process.env.SOLSTICE_EMAIL    || 'solstice@order.local';
const SOLSTICE_PASSWORD = process.env.SOLSTICE_PASSWORD || 'ChangeThisPassword123!';
const SOLSTICE_USERNAME = process.env.SOLSTICE_USERNAME || 'The Solstice';

const ARTICLES = [
  { num: 'ARTICLE I',   body: 'The Face and The Gardener are not the same person. They share no name, no shadow, no history. What one does, the other has never touched. This is not a preference. It is the foundation.', sort: 1 },
  { num: 'ARTICLE II',  body: 'The Face does not kill. It observes, advises, moves through rooms without leaving marks. Useful because trusted. That trust is not wasted on the blade\'s work.', sort: 2 },
  { num: 'ARTICLE III', body: 'The Gardener carries no pity into the field. Mercy left in the soil becomes rot. A contract accepted is a contract finished. Nothing about the target changes that.', sort: 3 },
  { num: 'ARTICLE IV',  body: 'When The Gardener draws, it is already over. There is no pause, no reconsideration, no window for the target to speak. The season turned the moment the mark was given.', sort: 4 },
  { num: 'ARTICLE V',   body: 'The Gardener does not serve anyone with coin. Service is earned. Those who simply demand the blade will find it pointed the wrong direction. The Order decides who is worthy of the harvest.', sort: 5 },
  { num: 'ARTICLE VI',  body: 'All contact runs through the Garden Channel. No names. No faces. Voice is distorted on both ends. The language of flowers holds until the harvest is closed and the channel goes dark.', sort: 6 },
  { num: 'ARTICLE VII', body: 'The comm device does not exist in any registry. When contact ends, the orchard closes. No record of it remains. No Gardener was ever there.', sort: 7 },
  { num: 'ARTICLE VIII',body: 'The Gardener does not ask if the target deserves it. That question belongs to the client. Once the mark is given, guilt and innocence both go into the soil the same way. The blade does not sort.', sort: 8 },
  { num: 'ARTICLE IX',  body: 'A witness is not a bystander. Anyone who sees the blade at work is part of the harvest. There is no unfortunate timing, no wrong place. The Gardener does not leave loose roots. The field is finished before the walk out.', sort: 9 },
];

// Helper: generate attribute rank descriptions (0-5)
const attrRanks = (descs) => [
  { rank: 0, label: 'Negligible', description: 'No aptitude whatsoever in this area.' },
  ...descs.map((d, i) => ({ rank: i + 1, label: ['Poor', 'Average', 'Good', 'Exceptional', 'Legendary'][i], description: d })),
];

// Helper: generate skill rank descriptions (0-5)
const skillRanks = (descs) => [
  { rank: 0, label: 'Untrained', description: 'No training in this skill.' },
  ...descs.map((d, i) => ({ rank: i + 1, label: ['Novice', 'Trained', 'Skilled', 'Expert', 'Master'][i], description: d })),
];

const DESCRIPTIONS = [
  // ── Attributes (9-attribute system: Physical / Social / Mental) ─────────────
  // Physical
  { type: 'attribute', key: 'str', label: 'Strength',
    description: 'Raw physical power — how hard you hit, how much you lift, how far you throw. At 1, you are slight and weak, easily overpowered. At 3, you are capable in a fight. At 5, you are physically terrifying: your strikes crack bone, your grip is inescapable, and those who face you in melee understand they are already at a disadvantage.',
    rank_descriptions: attrRanks([
      'Weak and frail; heavy doors are a struggle.',
      'Average strength for a healthy adult.',
      'Noticeably strong; you stand out in physical tasks.',
      'Exceptionally powerful; you can overpower most opponents.',
      'Legendary might; feats of strength that defy belief.',
    ]) },
  { type: 'attribute', key: 'dex', label: 'Dexterity',
    description: 'Speed, precision, and predatory grace. At 1, your movements are stiff and telegraphed. At 3, you move with trained efficiency. At 5, you are a shadow — fluid, untraceable, capable of threading a blade between ribs before a target registers motion. Lightsaber forms and ranged precision live here.',
    rank_descriptions: attrRanks([
      'Slow and awkward; fine motor tasks are a challenge.',
      'Average coordination and reflexes.',
      'Quick and nimble; your reflexes are sharp.',
      'Remarkably agile; you move with fluid precision.',
      'Superhuman reflexes and grace; you dodge blaster fire on instinct.',
    ]) },
  { type: 'attribute', key: 'sta', label: 'Stamina',
    description: 'Endurance, resilience, and the body\'s capacity to absorb punishment. At 1, you tire quickly and break under pressure. At 3, you can take a hit and keep fighting. At 5, you are nearly impossible to put down — poisons slow you, pain does not stop you, and your body keeps moving long after others would collapse. Directly contributes to your hit points.',
    rank_descriptions: attrRanks([
      'Sickly and fragile; you catch everything going around.',
      'Average stamina and health.',
      'Hardy and tough; you shrug off minor illness and fatigue.',
      'Iron constitution; you endure wounds that drop others.',
      'Nearly indestructible vitality; your endurance is the stuff of legend.',
    ]) },
  // Social
  { type: 'attribute', key: 'cha', label: 'Charisma',
    description: 'Personal magnetism, social influence, and the force of personality. At 1, you are forgettable and easily ignored. At 3, you command attention in a room and your words carry weight. At 5, you are magnetically dangerous — capable of turning enemies into tools, breaking loyalty with a conversation, and projecting the kind of authority that makes subordinates obey out of something deeper than fear.',
    rank_descriptions: attrRanks([
      'Awkward and forgettable; you struggle to hold a conversation.',
      'Average social presence.',
      'Charming and confident; people listen when you speak.',
      'Magnetic personality; you inspire loyalty and command attention.',
      'Overwhelming force of personality; your presence alone can change the course of events.',
    ]) },
  { type: 'attribute', key: 'man', label: 'Manipulation',
    description: 'The ability to twist others to your point of view through subtlety, cunning, and calculated pressure. At 1, your lies are transparent and your schemes obvious. At 3, you can navigate a conversation toward your goals without revealing your hand. At 5, you are a puppeteer — people do what you want and believe it was their idea. Intimidation, politics, and subterfuge live here.',
    rank_descriptions: attrRanks([
      'Transparent and easily read; you couldn\'t lie to save your life.',
      'Average ability to spin things in your favour.',
      'Smooth and convincing; you bend conversations to your will.',
      'Master manipulator; people do what you want and think it was their idea.',
      'Legendary schemer; you could turn allies against each other with a whisper.',
    ]) },
  { type: 'attribute', key: 'app', label: 'Appearance',
    description: 'First impressions, bearing, and the ability to appeal to others through presence and looks. At 1, you are plain and unremarkable — easily overlooked. At 3, you carry yourself with presence that draws the eye. At 5, you are striking in a way that lingers — beautiful, terrifying, or simply impossible to ignore. People react to you before you speak.',
    rank_descriptions: attrRanks([
      'Unkempt and off-putting; you make poor first impressions.',
      'Average-looking; you blend into a crowd.',
      'Attractive; heads turn when you walk into a cantina.',
      'Strikingly beautiful or handsome; you leave a lasting impression.',
      'Otherworldly beauty or terrifying grandeur; your appearance itself is a weapon.',
    ]) },
  // Mental
  { type: 'attribute', key: 'per', label: 'Perception',
    description: 'Awareness of your surroundings, alertness, and the ability to notice what others miss. At 1, details pass you by and you are easily surprised. At 3, your senses are sharp and reliable under pressure. At 5, nothing escapes you — the subtle shift before violence, the lie beneath calm words, the detail everyone else overlooked. You see it all.',
    rank_descriptions: attrRanks([
      'Inattentive and gullible; you miss what\'s right in front of you.',
      'Average awareness and common sense.',
      'Perceptive and insightful; you read situations well.',
      'Deeply intuitive; your instincts are rarely wrong.',
      'Profound awareness; nothing escapes your notice.',
    ]) },
  { type: 'attribute', key: 'int_score', label: 'Intelligence',
    description: 'Cold reasoning, accumulated knowledge, and the analytical mind of a Sith scholar. At 1, your understanding is surface-level and your plans are blunt. At 3, you are educated and capable of strategic thought. At 5, you are a dangerous intellect — reading rooms, exploiting weaknesses, mastering alchemical arts, and three steps ahead of everyone around you.',
    rank_descriptions: attrRanks([
      'Dim and easily confused; you struggle with basic logic.',
      'Average intellect and reasoning ability.',
      'Sharp mind; you learn quickly and think analytically.',
      'Brilliant; you solve problems others can\'t even articulate.',
      'Genius-level intellect; your mind rivals the greatest scholars in the galaxy.',
    ]) },
  { type: 'attribute', key: 'wit', label: 'Wits',
    description: 'Quick thinking, mental reflexes, and the ability to react swiftly under pressure. At 1, you freeze when surprised and struggle to adapt. At 3, you think on your feet and recover from the unexpected. At 5, your mind operates at combat speed — processing threats, improvising solutions, and responding to chaos before slower minds have registered what happened.',
    rank_descriptions: attrRanks([
      'Slow on the uptake; surprises leave you paralysed.',
      'Average reaction time and mental agility.',
      'Sharp and quick; you think fast under pressure.',
      'Razor-sharp reflexes of mind; you see traps before they spring.',
      'Preternatural mental speed; you anticipate events before they unfold.',
    ]) },

  // ── Saving Throws ────────────────────────────────────────────────────────────
  { type: 'save', key: 'fortitude', label: 'Fortitude',
    description: 'Resist poisons, disease, physical trauma, and the body\'s breaking point. Called when something threatens to shut down the body itself — toxins, exhaustion, environmental hazards, or the toll of sustained injury.',
    rank_descriptions: [] },
  { type: 'save', key: 'reflex', label: 'Reflex',
    description: 'Dodge, evade, and react to sudden physical threats. Called when speed and body awareness determine whether you get caught in a blast, a collapsing structure, or a surprise strike.',
    rank_descriptions: [] },
  { type: 'save', key: 'willpower', label: 'Willpower',
    description: 'Resist mental compulsion, Force coercion, fear, and psychological breaking. Called when something attempts to override your mind — Jedi mind tricks, Sith domination, terror effects, or prolonged interrogation.',
    rank_descriptions: [] },

  // ── Skills ───────────────────────────────────────────────────────────────────
  { type: 'skill', key: 'Athletics', label: 'Athletics',
    description: 'Covers running, jumping, climbing, swimming, and feats of raw physical exertion. Used when the body must move through environments or overcome physical obstacles at speed or under duress.',
    rank_descriptions: skillRanks([
      'You can climb a knotted rope and jog short distances.',
      'You can sprint reliably and swim in calm water.',
      'You excel at obstacle courses and can climb sheer surfaces with handholds.',
      'You perform feats of strength that impress soldiers and athletes.',
      'You are an elite physical specimen, capable of extraordinary feats of endurance and power.',
    ]) },
  { type: 'skill', key: 'Brawl', label: 'Brawl',
    description: 'Hand-to-hand fighting — strikes, grapples, chokes, and close-quarters violence without a weapon. Rank 1–2 is street-level brawling. Rank 3–5 is disciplined martial combat capable of killing efficiently and silently.',
    rank_descriptions: skillRanks([
      'You know how to throw a punch without hurting yourself.',
      'You have basic self-defense training.',
      'You are a competent fighter; most untrained opponents cannot match you.',
      'You are a dangerous hand-to-hand combatant with years of training.',
      'Your body is a weapon; you can disable or kill with bare hands.',
    ]) },
  { type: 'skill', key: 'Melee', label: 'Melee',
    description: 'Proficiency with physical melee weapons — vibro-blades, batons, knives, and non-lightsaber edged weapons. Covers attack technique, disarms, and weapon handling in close combat.',
    rank_descriptions: skillRanks([
      'You can swing a blade without dropping it.',
      'You have basic weapon training and can parry simple attacks.',
      'You wield a blade with confidence and skill in real combat.',
      'You are a feared melee combatant, capable of taking on multiple foes.',
      'You are a master swordsman or weapons expert, among the best in the galaxy.',
    ]) },
  { type: 'skill', key: 'Acrobatics', label: 'Acrobatics',
    description: 'Flips, vaults, falls, balance, and precision movement through space. Used to navigate difficult terrain, escape grapples, land from heights, or move in ways that defy expectation in combat and infiltration.',
    rank_descriptions: skillRanks([
      'You can do a somersault and land on your feet.',
      'You can balance on narrow beams and perform basic tumbles.',
      'You move with fluid grace and can perform acrobatic dodges.',
      'You could perform in a circus; flips and wall-runs are routine.',
      'You defy gravity with your agility, performing feats others think impossible.',
    ]) },
  { type: 'skill', key: 'Stealth', label: 'Stealth',
    description: 'Moving unseen and unheard. Covers shadow movement, suppressing tells, blending into environments, and avoiding detection during surveillance and assassination approaches.',
    rank_descriptions: skillRanks([
      'You can hide behind large objects and move quietly in soft shoes.',
      'You understand basic concealment and can tail someone in a crowd.',
      'You move like a shadow; casual observers rarely notice you.',
      'You can infiltrate guarded facilities and evade most sensor nets.',
      'You are virtually undetectable when you wish to be unseen.',
    ]) },
  { type: 'skill', key: 'Blasters', label: 'Blasters',
    description: 'Proficiency with blaster weapons — pistols, rifles, carbines, and heavy blasters. Covers accuracy, quick-draw, suppressive fire, and precision shooting at range under pressure. The standard weapon of the galaxy, and the skill that keeps you lethal beyond arm\'s reach.',
    rank_descriptions: skillRanks([
      'You can point and shoot without dropping the weapon.',
      'You hit stationary targets at moderate range.',
      'You are a reliable shot under pressure.',
      'You are a sharpshooter; headshots at range are routine.',
      'You are among the finest marksmen in the galaxy.',
    ]) },
  { type: 'skill', key: 'Lightsabers', label: 'Lightsabers',
    description: 'The blade forms of the Sith — from Juyo\'s ferocity to Makashi\'s precision. Covers all lightsaber combat stances, dueling, and the specific demands of controlling a weapon that cuts through nearly anything.',
    rank_descriptions: skillRanks([
      'You can ignite a lightsaber without injuring yourself.',
      'You know the basics of Form I (Shii-Cho) and can deflect clumsy attacks.',
      'You fight competently with a lightsaber and can deflect blaster bolts.',
      'You have mastered one or more lightsaber forms and are a formidable duelist.',
      'You are a lightsaber virtuoso, capable of fighting multiple opponents simultaneously.',
    ]) },
  { type: 'skill', key: 'Piloting', label: 'Piloting',
    description: 'Operating spacecraft, starfighters, and atmospheric craft. Covers evasive maneuvers, navigation under fire, docking, and the instinctive feel for how a ship responds.',
    rank_descriptions: skillRanks([
      'You can fly in a straight line and land without crashing.',
      'You can handle standard flight operations and basic combat maneuvers.',
      'You are a skilled pilot comfortable in dogfights and asteroid fields.',
      'You are an ace; your reflexes and instincts make you lethal in the cockpit.',
      'You are a legendary pilot — the stuff of spacer tales.',
    ]) },
  { type: 'skill', key: 'Ground Vehicles', label: 'Ground Vehicles',
    description: 'Operating speeder bikes, speeders, walkers, and other ground vehicles. Covers high-speed pursuit, evasion, terrain navigation, and vehicle combat.',
    rank_descriptions: skillRanks([
      'You can drive in a straight line on a clear road.',
      'You handle vehicles competently in traffic and mild terrain.',
      'You drive with skill in difficult terrain and high-speed chases.',
      'You can perform tactical vehicle maneuvers under fire.',
      'You are a master wheelman, capable of impossible maneuvers.',
    ]) },
  { type: 'skill', key: 'Resilience', label: 'Resilience',
    description: 'The body\'s trained capacity to absorb damage and keep fighting. Directly increases your hit pool. A Sith who invests here is difficult to put down — built to outlast opponents through sheer physical fortitude.',
    rank_descriptions: skillRanks([
      'You can take a punch without flinching and push through minor injuries.',
      'You shrug off blows that would stagger most people. Bruises and scrapes barely register.',
      'You have been hurt badly and kept fighting. Your body is conditioned to absorb serious punishment.',
      'You endure injuries that would incapacitate others — broken bones, blaster burns, concussive blasts — and stay on your feet.',
      'Your tolerance for physical punishment is legendary. You have survived things that should have killed you, more than once.',
    ]) },
  { type: 'skill', key: 'Academics', label: 'Academics',
    description: 'Broad scholarly knowledge — history, galactic geography, cultures, ancient civilizations, and general learned expertise. Used when understanding context, identifying artifacts, or recalling relevant historical facts.',
    rank_descriptions: skillRanks([
      'You have basic literacy and general knowledge.',
      'You have a solid education across multiple subjects.',
      'You are well-read and knowledgeable across multiple academic fields.',
      'You are a recognized scholar or expert in your area of study.',
      'You possess encyclopedic knowledge rivaling the greatest minds in the galaxy.',
    ]) },
  { type: 'skill', key: 'Computing', label: 'Computing',
    description: 'Operating, programming, and slicing computer systems. Covers data extraction, bypassing security protocols, hacking networks, and understanding system architecture from terminals to ship computers.',
    rank_descriptions: skillRanks([
      'You can use standard terminals and search databases.',
      'You write simple programs and manage networked systems.',
      'You build complex software, automate processes, and analyze encrypted data.',
      'You architect systems and write code that others struggle to comprehend.',
      'You are a programming savant — you speak to machines more naturally than to people.',
    ]) },
  { type: 'skill', key: 'Demolitions', label: 'Demolitions',
    description: 'Setting, identifying, and disarming explosive devices. Covers shaped charges, timed detonations, structural analysis for maximum effect, and the delicate work of defusing what someone else planted.',
    rank_descriptions: skillRanks([
      'You know which end of a thermal detonator is dangerous.',
      'You can set and detonate standard charges safely.',
      'You craft improvised explosives and disarm standard devices.',
      'You are an expert demolitionist, precise with shaped charges.',
      'You can level buildings with surgical precision or disarm anything.',
    ]) },
  { type: 'skill', key: 'Technology', label: 'Technology',
    description: 'Understanding, repairing, and modifying mechanical and electronic systems. Covers field repairs, improvised construction, identifying tech, and working with equipment outside its intended parameters.',
    rank_descriptions: skillRanks([
      'You can operate consumer-grade technology.',
      'You handle military-grade tech and understand specifications.',
      'You modify and optimize advanced technological systems.',
      'You design cutting-edge technology and understand experimental systems.',
      'You are a tech visionary, creating innovations that reshape how things work.',
    ]) },
  { type: 'skill', key: 'Force Alchemy', label: 'Force Alchemy',
    description: 'The Sith art of reshaping matter and life through the dark side. Used for crafting alchemical weapons, enhancing objects with Force properties, and the more dangerous applications of biological modification. Rare and dangerous even among Sith.',
    rank_descriptions: skillRanks([
      'You understand the theory of Force alchemy.',
      'You can perform simple alchemical enhancements on materials.',
      'You create minor Sith artifacts and alchemically treated weapons.',
      'You forge powerful artifacts imbued with the dark side.',
      'You are a master alchemist, creating artifacts of legendary power.',
    ]) },
  { type: 'skill', key: 'Force Knowledge', label: 'Force Knowledge',
    description: 'Theoretical and historical understanding of the Force — its traditions, philosophies, lore, and known applications across both Sith and Jedi lineages. Knowing what something is, where it comes from, and what it is capable of.',
    rank_descriptions: skillRanks([
      'You know the Force exists and its basic nature.',
      'You understand Jedi and Sith philosophies in broad strokes.',
      'You have deep knowledge of Force traditions, history, and theory.',
      'You are a Force scholar, understanding subtle aspects most ignore.',
      'Your knowledge of the Force rivals the greatest masters in history.',
    ]) },
  { type: 'skill', key: 'Investigation', label: 'Investigation',
    description: 'Active searching, evidence analysis, and piecing together what happened from fragments. Used to find hidden objects, reconstruct events, identify patterns in information, and pursue leads through methodical examination.',
    rank_descriptions: skillRanks([
      'You can spot obvious clues at a scene.',
      'You follow evidence trails and conduct basic forensic analysis.',
      'You are a skilled investigator who reconstructs events from evidence.',
      'You solve complex cases and detect evidence others miss entirely.',
      'You are a master detective; virtually no crime can escape your analysis.',
    ]) },
  { type: 'skill', key: 'Law', label: 'Law',
    description: 'Knowledge of Imperial codes, Sith Order protocols, criminal statutes, and the legal frameworks that govern the galaxy. Useful for identifying leverage, navigating bureaucratic systems, and understanding what others can and cannot do officially.',
    rank_descriptions: skillRanks([
      'You know the basics of what\'s legal and illegal.',
      'You understand common legal procedures and your rights.',
      'You can argue cases and navigate complex legal systems.',
      'You are an expert in galactic law and legal strategy.',
      'You know every loophole and precedent; courtrooms are your battlefield.',
    ]) },
  { type: 'skill', key: 'Medicine', label: 'Medicine',
    description: 'Medical knowledge from field triage to surgical intervention. Rank 1–2 stabilizes wounds and stops bleeding. Rank 3–5 covers complex treatment, poison identification, and the anatomical knowledge that serves equally well in healing and harm.',
    rank_descriptions: skillRanks([
      'You understand anatomy basics and can identify common diseases.',
      'You diagnose ailments accurately and prescribe effective treatments.',
      'You perform surgery and manage complex medical cases in a proper facility.',
      'You are a skilled physician whose diagnoses catch what others miss.',
      'You are a medical genius — your knowledge saves lives that science says are lost.',
    ]) },
  { type: 'skill', key: 'Military', label: 'Military',
    description: 'Tactical and strategic knowledge of warfare — unit tactics, command structures, battlefield assessment, siege theory, and the doctrines that govern how organized forces fight. Used when planning operations or reading a military situation.',
    rank_descriptions: skillRanks([
      'You understand basic military ranks and chain of command.',
      'You know standard squad tactics and military procedures.',
      'You plan and execute military operations with competence.',
      'You are a skilled tactician capable of commanding large forces.',
      'You are a strategic genius whose plans shift the course of wars.',
    ]) },
  { type: 'skill', key: 'Pharmacopoeia/Poisons', label: 'Pharmacopoeia/Poisons',
    description: 'Knowledge of substances — drugs, sedatives, toxins, and poisons. Covers identification, synthesis, delivery methods, dosing, and antidotes. An essential skill for those who prefer the work done before anyone draws a weapon.',
    rank_descriptions: skillRanks([
      'You know common drugs and their effects.',
      'You can identify poisons and prepare basic remedies.',
      'You craft effective compounds — stimulants, sedatives, toxins.',
      'You create sophisticated drugs and nearly undetectable poisons.',
      'You are a master of pharmacology; your concoctions are legendary.',
    ]) },
  { type: 'skill', key: 'Torture', label: 'Torture',
    description: 'The applied science of extracting information, breaking resistance, and demonstrating consequences. Covers technique, psychological pressure, knowing the line between useful and fatal, and the patience the work requires.',
    rank_descriptions: skillRanks([
      'You understand basic intimidation tactics.',
      'You can conduct a structured interrogation.',
      'You break most subjects efficiently using psychological pressure.',
      'You extract information from hardened operatives and trained resisters.',
      'Your reputation alone makes prisoners talk; your methods are legendary.',
    ]) },
  { type: 'skill', key: 'Awareness', label: 'Awareness',
    description: 'Noticing what others miss — details, tells, ambient threats, and the subtle wrongness that precedes danger. Both passive (do you notice?) and active (what do you find when you look?). The difference between walking into an ambush and seeing it coming.',
    rank_descriptions: skillRanks([
      'You occasionally notice things others miss.',
      'You are generally alert and hard to catch off guard.',
      'You pick up on subtle cues — a shifted shadow, a faint sound.',
      'Very little escapes your notice; you react before others realize something is wrong.',
      'Your senses are razor-sharp; you perceive threats before they fully materialize.',
    ]) },
  { type: 'skill', key: 'Empathy', label: 'Empathy',
    description: 'Reading people — their emotional state, motivations, deceptions, and the gap between what they say and what they mean. Not sympathy. A predator\'s tool for understanding prey.',
    rank_descriptions: skillRanks([
      'You can tell when someone is obviously upset or angry.',
      'You read basic emotional states and detect obvious lies.',
      'You sense underlying motivations and hidden emotions.',
      'You read people like open books, sensing what they try to hide.',
      'You understand others at a profound level, perceiving their deepest drives.',
    ]) },
  { type: 'skill', key: 'Force Intuition', label: 'Force Intuition',
    description: 'The raw, instinctive connection to the Force — feeling presences, sensing danger before it arrives, and the wordless knowing that something is wrong or right. Less studied than Force Knowledge, more felt than understood.',
    rank_descriptions: skillRanks([
      'You occasionally get gut feelings that prove accurate.',
      'You sense strong emotional disturbances through the Force.',
      'You receive clear intuitive warnings and guidance from the Force.',
      'Your Force intuition is a reliable sixth sense in combat and intrigue.',
      'The Force speaks to you constantly, guiding your every instinct.',
    ]) },
  { type: 'skill', key: 'Meditation', label: 'Meditation',
    description: 'Focused mental discipline — controlling the mind under pressure, processing trauma, deepening Force connection through stillness, and the practice of achieving clarity in chaos. Used for recovery, focus, and some Force applications that require calm.',
    rank_descriptions: skillRanks([
      'You can sit still and clear your mind briefly.',
      'You meditate regularly and achieve basic focus.',
      'Deep meditation comes easily; you can center yourself under stress.',
      'Your meditation deepens your Force connection significantly.',
      'You achieve profound meditative states that transcend normal consciousness.',
    ]) },
  { type: 'skill', key: 'Politics', label: 'Politics',
    description: 'Reading power structures, navigating factional dynamics, understanding what people want and who holds leverage over whom. Used in courts, councils, and any situation where the real weapon is information and positioning.',
    rank_descriptions: skillRanks([
      'You understand basic political structures.',
      'You navigate bureaucracies and understand factional dynamics.',
      'You are politically savvy, reading power plays and alliances.',
      'You manipulate political systems to achieve your goals.',
      'You are a master politician, shaping the course of empires.',
    ]) },
  { type: 'skill', key: 'Survival', label: 'Survival',
    description: 'Staying alive in hostile environments — navigation, finding food and water, building shelter, identifying natural hazards, and the situational reading that keeps you functional when civilization is not an option.',
    rank_descriptions: skillRanks([
      'You can start a fire and find water in mild conditions.',
      'You survive in wilderness and can track obvious trails.',
      'You thrive in harsh environments and track skilled quarry.',
      'You survive anywhere — deserts, jungles, arctic wastelands.',
      'You are at home in the most lethal environments the galaxy offers.',
    ]) },
  { type: 'skill', key: 'Metabolism', label: 'Metabolism',
    description: 'The body\'s capacity to process substances — resisting poisons, metabolizing drugs, tolerating sedatives, and recovering from chemical interference. At higher ranks, your body neutralizes what would incapacitate others. Useful for surviving assassination attempts and the aftereffects of your own indulgences.',
    rank_descriptions: skillRanks([
      'You recover quickly from hangovers and minor food poisoning. Your immune system is above average.',
      'You can drink most people under the table and shake off mild sedatives faster than expected.',
      'You have built up tolerances to common poisons and drugs through exposure or training. Tranquilizers take longer to work on you.',
      'Your body processes toxins at remarkable speed. Doses that would kill others merely make you ill.',
      'Your biochemistry is extraordinary. You can survive poisons, venoms, and chemical agents that are lethal to virtually anyone else.',
    ]) },
  { type: 'skill', key: 'Acting', label: 'Acting',
    description: 'Inhabiting a role convincingly — controlling body language, voice, mannerism, and emotional display to pass as someone else or project a chosen persona. The foundation of long-term infiltration and identity work.',
    rank_descriptions: skillRanks([
      'You can wear a simple disguise and play a basic role without breaking character.',
      'You adopt convincing false identities and portray unfamiliar social roles.',
      'You impersonate specific people, mimicking their voice, gait, and mannerisms.',
      'You maintain a false identity under intense scrutiny for days or weeks.',
      'You become whoever you pretend to be — even close friends might be fooled.',
    ]) },
  { type: 'skill', key: 'Crafts', label: 'Crafts',
    description: 'Creating things with skill and intention — artisanship, forgery, disguise construction, and the making of objects that require more than technical knowledge. When the work must look right as well as function.',
    rank_descriptions: skillRanks([
      'You can make simple items with basic tools.',
      'You produce functional, well-made goods.',
      'Your craftsmanship is notable; people seek out your work.',
      'You create exceptional items of beauty and quality.',
      'Your masterwork creations are legendary, sought by the powerful.',
    ]) },
  { type: 'skill', key: 'Etiquette', label: 'Etiquette',
    description: 'Navigating formal social environments — court protocols, Imperial ceremony, high-society behavior, and the unspoken rules that govern who belongs in a room. Failure here is visible. Success is invisible.',
    rank_descriptions: skillRanks([
      'You know to be polite and say \'please\' and \'thank you.\'',
      'You navigate formal social situations without embarrassment.',
      'You move comfortably in elite society and diplomatic circles.',
      'You are a diplomatic expert, adapting to any culture\'s customs.',
      'You are the perfect courtier, at ease with emperors and crime lords alike.',
    ]) },
  { type: 'skill', key: 'Expression', label: 'Expression',
    description: 'Communicating through performance, art, or rhetoric — persuasion through narrative, moving an audience, and the use of creative output as a tool of influence. Broader than Acting; covers genuine emotional resonance.',
    rank_descriptions: skillRanks([
      'You can state your point clearly in conversation.',
      'You speak persuasively and present arguments effectively.',
      'You captivate audiences and win debates.',
      'Your speeches move people to action and change minds.',
      'Your words can incite revolutions or bring peace to warring factions.',
    ]) },
  { type: 'skill', key: 'Intimidation', label: 'Intimidation',
    description: 'Making others afraid. Covers direct physical menace, implied threat, psychological pressure, and the kind of presence that makes people reconsider their choices before they make them.',
    rank_descriptions: skillRanks([
      'You can look angry and raise your voice.',
      'You intimidate those weaker than you with direct threats.',
      'Your presence alone makes people nervous; your threats carry weight.',
      'Hardened warriors think twice before opposing you.',
      'Your reputation precedes you; your mere presence can break someone\'s will.',
    ]) },
  { type: 'skill', key: 'Leadership', label: 'Leadership',
    description: 'Commanding others — through authority, example, fear, or inspiration. Used when directing people in crisis, building loyalty, and ensuring those below you do what you need them to do.',
    rank_descriptions: skillRanks([
      'You can give clear instructions to a small group.',
      'You lead small teams effectively and delegate tasks.',
      'You inspire loyalty and coordinate complex operations.',
      'You command large groups with authority and strategic vision.',
      'You are a legendary leader whose followers would die for your cause.',
    ]) },
  { type: 'skill', key: 'Seduction', label: 'Seduction',
    description: 'Creating desire, attachment, and dependency. Covers romantic manipulation, cultivating obsession, and leveraging intimacy as an intelligence and control tool. Not limited to the physical.',
    rank_descriptions: skillRanks([
      'You can flirt without making it awkward.',
      'You are charming and attract attention when you try.',
      'You are genuinely alluring; people are drawn to you.',
      'You can seduce almost anyone with time and opportunity.',
      'Your allure is legendary; you wield desire as a weapon.',
    ]) },
  { type: 'skill', key: 'Streetwise', label: 'Streetwise',
    description: 'Navigating the underworld — criminal contacts, black markets, reading neighborhoods, speaking the right language to the right people, and knowing where to find what legitimate channels cannot provide.',
    rank_descriptions: skillRanks([
      'You know that a criminal underworld exists.',
      'You can find a black market and avoid obvious scams.',
      'You navigate the underworld comfortably and have useful contacts.',
      'You are a respected figure in criminal circles.',
      'You know every shadow in the galaxy\'s underworld.',
    ]) },
  { type: 'skill', key: 'Subterfuge', label: 'Subterfuge',
    description: 'Concealment of intent, misdirection, and active deception in social interaction. Where Acting is performing a role, Subterfuge is hiding your real one — lying under scrutiny, deflecting suspicion, and keeping secrets under pressure.',
    rank_descriptions: skillRanks([
      'You can keep a straight face when lying about something simple.',
      'You lie convincingly and redirect conversations away from dangerous topics.',
      'You maintain complex webs of deception across multiple people and timelines.',
      'You manipulate entire situations — people act on your lies without ever questioning them.',
      'You are virtually impossible to read; the truth is whatever you decide it is.',
    ]) },

  // ── Additional skills ──────────────────────────────────────────────────────
  { type: 'skill', key: 'Jetpack', label: 'Jetpack',
    description: 'Operating and maneuvering with jetpacks and rocket packs. Covers controlled flight, aerial combat positioning, emergency use, and the specific demands of a propulsion system strapped to your back in a firefight.',
    rank_descriptions: skillRanks([
      'You can activate a jetpack and hover without spinning out.',
      'You can perform short controlled flights and soft landings.',
      'You maneuver confidently in three dimensions during combat.',
      'You fight in the air as naturally as on the ground.',
      'You are a master of aerial combat, using the jetpack as an extension of yourself.',
    ]) },
  { type: 'skill', key: 'Riding', label: 'Riding',
    description: 'Controlling mounted animals and creatures — approach, handling, combat from the saddle, and the dominance relationship required to direct a living mount under duress. Some beasts respond to fear. Some require something else.',
    rank_descriptions: skillRanks([
      'You can stay on a docile mount at a walk.',
      'You ride confidently at a trot and can handle gentle terrain.',
      'You are a skilled rider, comfortable in a gallop and rough ground.',
      'You can fight from the saddle and handle aggressive mounts.',
      'You and your mount are one; you ride into battle without fear.',
    ]) },
  { type: 'skill', key: 'Slugthrowers', label: 'Slugthrowers',
    description: 'Proficiency with projectile weapons firing physical rounds — ballistic pistols, rifles, and chemically-propelled firearms. Often overlooked. Equally lethal. Harder to deflect than a blaster bolt, and entirely silent with the right suppressor.',
    rank_descriptions: skillRanks([
      'You can load and fire a slugthrower.',
      'You hit targets at moderate range and understand ballistics basics.',
      'You are proficient with multiple projectile weapon types.',
      'You are an expert marksman with kinetic weapons.',
      'You are a master of slugthrower combat, feared for your precision.',
    ]) },
  { type: 'skill', key: 'Swoop Bikes', label: 'Swoop Bikes',
    description: 'Operating swoop bikes and high-performance repulsorlift racing craft. Covers extreme-speed navigation, pursuit, evasion, and the precise throttle control that keeps you alive at full burn through terrain that would kill anyone slower.',
    rank_descriptions: skillRanks([
      'You can ride a swoop without immediately crashing.',
      'You handle basic swoop operations and moderate speeds.',
      'You race competitively and handle sharp turns at speed.',
      'You are a professional-grade swoop racer or scout.',
      'You push swoop bikes to their absolute limits, performing impossible maneuvers.',
    ]) },
  { type: 'skill', key: 'Ancient Technology', label: 'Ancient Technology',
    description: 'Identifying, operating, and salvaging technology from prior eras — pre-Empire hardware, Old Republic systems, Sith relics, and devices whose documentation no longer exists. What most cannot read, you can operate.',
    rank_descriptions: skillRanks([
      'You recognize ancient tech when you see it.',
      'You understand basic principles of pre-Republic technology.',
      'You can interface with and partially operate ancient devices.',
      'You are an expert in ancient technologies and their applications.',
      'You unlock secrets of ancient tech that others thought permanently lost.',
    ]) },
  { type: 'skill', key: 'Astrography', label: 'Astrography',
    description: 'Knowledge of star systems, hyperspace routes, galactic geography, and navigation. Used to plan travel, identify unknown regions, and understand the spatial relationships that define strategy at scale. You know where things are, and where to disappear.',
    rank_descriptions: skillRanks([
      'You know the major systems and trade routes.',
      'You can plot standard hyperspace courses.',
      'You know obscure systems and can find alternate routes.',
      'You are an expert navigator and galactic cartographer.',
      'Your knowledge of the galaxy\'s geography is unmatched.',
    ]) },
  { type: 'skill', key: 'Biology', label: 'Biology',
    description: 'The scientific study of living organisms — anatomy, ecology, xenobiology, and the physical workings of life across species. Informs medicine, poisons, and the precise understanding of what a body can and cannot be made to endure.',
    rank_descriptions: skillRanks([
      'You know basic biology — cell structure, ecosystems.',
      'You can identify common species and understand their biology.',
      'You have deep knowledge of xenobiology and genetics.',
      'You are an expert biologist capable of groundbreaking research.',
      'You understand life at its deepest levels, from viruses to sentient species.',
    ]) },
  { type: 'skill', key: 'Biotech', label: 'Biotech',
    description: 'The application of biological knowledge to engineering — cybernetics, genetic modification, alchemical tissue work, and the interface between living systems and constructed ones. Where biology ends and machine begins is a question this skill renders irrelevant.',
    rank_descriptions: skillRanks([
      'You understand that cybernetics exist and their basic purpose.',
      'You can maintain and perform basic repairs on common implants.',
      'You can install standard cybernetics and diagnose biotech malfunctions.',
      'You design and modify advanced cybernetic systems.',
      'You push the boundaries of biological and technological integration.',
    ]) },
  { type: 'skill', key: 'Droids', label: 'Droids',
    description: 'Programming, repairing, modifying, and commanding droid units. Covers everything from restraining bolts to slicing behavioral matrices to building purpose-specific units from salvaged components. A well-modified droid asks no questions.',
    rank_descriptions: skillRanks([
      'You can interact with droids and perform basic maintenance.',
      'You can repair common droid malfunctions and read schematics.',
      'You build and modify droids, understanding their programming deeply.',
      'You are a droid expert; you design custom droids and AI routines.',
      'You create droids of extraordinary sophistication and capability.',
    ]) },
  { type: 'skill', key: 'Engineering', label: 'Engineering',
    description: 'Structural and mechanical design — ships, facilities, weapons systems, and large-scale construction. Used to assess structural weaknesses, design effective systems, and understand how built things work and, more usefully, how they fail.',
    rank_descriptions: skillRanks([
      'You understand basic mechanical principles.',
      'You can read blueprints and assist with construction.',
      'You design and build functional structures and mechanical systems.',
      'You engineer complex systems — ships, stations, fortifications.',
      'You are a master engineer whose designs push technological boundaries.',
    ]) },
  { type: 'skill', key: 'Enigmas', label: 'Enigmas',
    description: 'Solving puzzles, ciphers, logic traps, and problems designed to exclude most minds. Used for decryption without a computer, Sith riddles, and any situation where the obstacle is a constructed mental challenge with a correct answer buried inside it.',
    rank_descriptions: skillRanks([
      'You can solve simple puzzles and riddles.',
      'You work through moderate logic problems and ciphers.',
      'You crack complex codes and see patterns others miss.',
      'You solve puzzles that stump most scholars.',
      'No riddle, cipher, or logical trap can confound you for long.',
    ]) },
  { type: 'skill', key: 'Esoterica', label: 'Esoterica',
    description: 'Knowledge of occult traditions, forbidden lore, mystical symbolism, and the fringe teachings that fall outside recognized Force doctrine. What scholars dismiss, this skill remembers. Some of it should have stayed forgotten.',
    rank_descriptions: skillRanks([
      'You have heard rumors of Sith lore and dark-side mysteries.',
      'You understand basic Sith philosophy and occult concepts.',
      'You are well-versed in esoteric knowledge and hidden lore.',
      'You are a keeper of forbidden knowledge and ancient secrets.',
      'Your understanding of the galaxy\'s deepest mysteries is profound.',
    ]) },
  { type: 'skill', key: 'Finance', label: 'Finance',
    description: 'Understanding and manipulating money — markets, investments, black-market valuations, and the economic systems that fund power. Useful for following credits, hiding them, and knowing exactly what leverage costs before you pay for it.',
    rank_descriptions: skillRanks([
      'You understand credits, debt, and basic budgeting.',
      'You can manage a business and understand market trends.',
      'You are a skilled financier who can spot profitable opportunities.',
      'You manipulate markets and manage vast sums.',
      'You are a financial mastermind, capable of economic warfare.',
    ]) },
  { type: 'skill', key: 'Force Traditions', label: 'Force Traditions',
    description: 'Scholarly knowledge of Force-using traditions beyond Sith and Jedi — Nightsisters, Baran Do, Dathomiri witches, and the scattered orders that developed their own relationship with the Force. Knowing who they are, what they can do, and what they want.',
    rank_descriptions: skillRanks([
      'You know that other Force traditions exist beyond Sith and Jedi.',
      'You can name the major traditions and their broad philosophies.',
      'You understand the practices and capabilities of multiple Force orders.',
      'You are an expert in obscure traditions, their rites, and their weaknesses.',
      'Your knowledge of the galaxy\'s Force traditions is encyclopedic and unrivaled.',
    ]) },
  { type: 'skill', key: 'Repair', label: 'Repair',
    description: 'Hands-on maintenance and restoration of equipment, vehicles, and weapons. Where Technology covers understanding, Repair covers fixing — getting the thing operational again under field conditions with whatever is available.',
    rank_descriptions: skillRanks([
      'You can tighten bolts and replace simple parts.',
      'You handle routine maintenance and minor repairs.',
      'You fix complex malfunctions and improvise replacement parts.',
      'You restore heavily damaged equipment to working condition.',
      'You can repair virtually anything given minimal tools and time.',
    ]) },
  { type: 'skill', key: 'Research', label: 'Research',
    description: 'Systematic gathering, evaluation, and synthesis of information. Covers archival work, source verification, and the disciplined process of constructing knowledge from fragments across multiple sources. Patience as a weapon.',
    rank_descriptions: skillRanks([
      'You can search a database for basic information.',
      'You conduct structured research and find relevant sources.',
      'You dig deep, cross-referencing multiple sources for hidden connections.',
      'You uncover information that others have tried to bury.',
      'You are a research savant; no secret stays hidden from your inquiry.',
    ]) },
  { type: 'skill', key: 'Science', label: 'Science',
    description: 'Broad applied scientific knowledge — physics, chemistry, astronomy, and the physical laws governing the galaxy. Used when the answer requires understanding how things actually work at a fundamental level rather than how they appear to work.',
    rank_descriptions: skillRanks([
      'You understand basic scientific principles taught in schools.',
      'You have a solid grounding in one or more scientific disciplines.',
      'You conduct experiments and understand advanced theoretical concepts.',
      'You are a brilliant scientist capable of original research and discovery.',
      'You are a visionary whose scientific insights reshape understanding of the galaxy.',
    ]) },
  { type: 'skill', key: 'Animal Ken', label: 'Animal Ken',
    description: 'Understanding and communicating with animals — reading their behavior, earning their trust or compliance, and the patient attunement required to direct a creature that does not share your language. Some animals sense darkness. This skill decides what they do with that.',
    rank_descriptions: skillRanks([
      'Animals are not immediately hostile to you.',
      'You can calm nervous beasts and train domesticated animals.',
      'You understand animal behavior and can handle exotic creatures.',
      'You bond with wild beasts and train them for complex tasks.',
      'You have an almost supernatural rapport with creatures of all kinds.',
    ]) },
  { type: 'skill', key: 'High Ritual', label: 'High Ritual',
    description: 'Knowledge and performance of formal Force ceremonies, Sith rites, and the structured invocations that certain traditions use to channel the Force through deliberate process rather than instinct. Rare. Methodical. The kind of power that requires preparation, not reaction.',
    rank_descriptions: skillRanks([
      'You understand the concept of Force rituals.',
      'You can participate in group rituals and follow ceremonial procedures.',
      'You lead minor rituals and understand their symbolic components.',
      'You conduct powerful rituals that channel significant Force energy.',
      'You perform legendary rites that reshape the Force itself.',
    ]) },
  { type: 'skill', key: 'Lucid Dreaming', label: 'Lucid Dreaming',
    description: 'Entering and navigating dream states with intent — Force-touched visions, prophetic fragments, and the mind\'s capacity to receive and interpret what waking senses cannot. Some things are only accessible here. Some things encountered here do not stay there.',
    rank_descriptions: skillRanks([
      'You sometimes realize you are dreaming.',
      'You can occasionally control your dreams and remember them clearly.',
      'You navigate your dreamscape with purpose and clarity.',
      'You enter others\' dreams and extract information from visions.',
      'You are a master dreamwalker, using the dream state as a tool of power.',
    ]) },
  { type: 'skill', key: 'Search', label: 'Search',
    description: 'Methodical physical searching — locations, rooms, persons, and terrain. Where Awareness covers passive noticing, Search covers the deliberate, systematic sweep that finds what someone hid carefully and believed was safe.',
    rank_descriptions: skillRanks([
      'You can find things that are slightly out of place.',
      'You conduct thorough searches and notice hidden compartments.',
      'You find concealed objects and secret passages reliably.',
      'Almost nothing can be hidden from your systematic search.',
      'You find things others didn\'t even know were missing.',
    ]) },
  { type: 'skill', key: 'Artistic Expression', label: 'Artistic Expression',
    description: 'Using creative output as a vehicle for influence — art, music, writing, and performance that moves audiences emotionally and shapes how they see the world. Not the performance of a role, but genuine creative force. People remember what moves them. That memory is useful.',
    rank_descriptions: skillRanks([
      'You can carry a tune or sketch a recognizable figure.',
      'You create competent art that others appreciate.',
      'Your art is genuinely moving and shows real talent.',
      'You are a celebrated artist whose work stirs deep emotions.',
      'You create masterpieces that transcend time and culture.',
    ]) },
  { type: 'skill', key: 'Carousing', label: 'Carousing',
    description: 'Operating effectively in social environments built around pleasure — taverns, gatherings, underworld venues, and the informal settings where guards come down and information flows. Making people comfortable enough to talk. They always do.',
    rank_descriptions: skillRanks([
      'You can make small talk without embarrassing yourself.',
      'You are comfortable in social settings and make friends easily.',
      'You are the life of the party; people open up to you over drinks.',
      'You extract secrets and build networks through social gatherings.',
      'Every cantina knows your name; your social network spans the galaxy.',
    ]) },
  { type: 'skill', key: 'Media', label: 'Media',
    description: 'Understanding and operating through information channels — propaganda, broadcast manipulation, shaping public narrative, and the techniques of controlling what people believe by controlling what they hear. The most patient form of violence.',
    rank_descriptions: skillRanks([
      'You can record a basic holo-message.',
      'You create competent media content and understand audiences.',
      'You produce engaging content that reaches wide audiences.',
      'You craft propaganda and media campaigns that shape opinion.',
      'You control narratives across the galaxy through masterful media manipulation.',
    ]) },
];

async function seed() {
  // Nine Articles
  for (const a of ARTICLES) {
    await pool.query(
      `INSERT INTO codex_articles (article_num, body, category, sort_order)
       VALUES ($1, $2, 'standing_articles', $3)
       ON CONFLICT (article_num, category) DO NOTHING`,
      [a.num, a.body, a.sort]
    );
  }
  console.log('Codex articles seeded.');

  // Descriptions (attributes, saves, skills)
  for (const d of DESCRIPTIONS) {
    await pool.query(
      `INSERT INTO spire_descriptions (type, key, label, description, rank_descriptions)
       VALUES ($1, $2, $3, $4, $5)
       ON CONFLICT (type, key) DO UPDATE SET label=EXCLUDED.label, description=EXCLUDED.description, rank_descriptions=EXCLUDED.rank_descriptions`,
      [d.type, d.key, d.label, d.description, JSON.stringify(d.rank_descriptions || [])]
    );
  }
  console.log('Descriptions seeded.');

  // Solstice account
  const { rows: existing } = await pool.query('SELECT id FROM users WHERE email=$1', [SOLSTICE_EMAIL]);
  if (existing.length) {
    console.log('Solstice account already exists, skipping.');
  } else {
    const hash = await bcrypt.hash(SOLSTICE_PASSWORD, 12);
    const { rows: [user] } = await pool.query(
      `INSERT INTO users (email, password_hash, username, role)
       VALUES ($1, $2, $3, 'admin') RETURNING id`,
      [SOLSTICE_EMAIL, hash, SOLSTICE_USERNAME]
    );
    console.log(`Solstice account created: ${SOLSTICE_EMAIL}`);
    console.log(`Password: ${SOLSTICE_PASSWORD}  ← change this immediately`);
  }

}

module.exports = seed;

// Allow running directly: node src/db/seed.js
if (require.main === module) {
  require('dotenv').config({ path: require('path').join(__dirname, '..', '..', `.env.${process.env.NODE_ENV || 'development'}`) });
  seed().then(() => pool.end()).catch(err => { console.error(err); process.exit(1); });
}
